### ISSUE TITLE
Question: couldn't use xmllint-action 

### ISSUE THREAD

**Issue by vitalyk-multinarity** [ChristophWurst/xmllint-action#4]
I tried to use xmllint-action with xmllint-problem-matcher, based on 'Extended Usage Example Enabling Annotations', but I'm getting the same output as before.
My workflow file is:

```
    - uses: korelstar/xmllint-problem-matcher@v1
    - name: Lint ROM manifest
       uses: ChristophWurst/xmllint-action@v1 
       with:
         xml-file:my-manifest.xml
         xml-schema-file: my-schema.xsd
```

Any suggestions?
Thank you,
Vitaly
